---
apiVersion: v1
kind: Namespace
metadata:
  name: adguard
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: adguard
  labels:
    app.kubernetes.io/component: home
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard
    app.kubernetes.io/part-of: adguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard
  template:
    metadata:
      labels:
        app.kubernetes.io/component: home
        app.kubernetes.io/instance: adguard
        app.kubernetes.io/name: adguard
        app.kubernetes.io/part-of: adguard
    spec:
      containers:
        - name: adguard
          image: docker.io/adguard/adguardhome:v0.107.55 # {"$imagepolicy": "adguard:adguard"}
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
              - NET_RAW
              drop:
              - ALL
            privileged: false
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 68
              protocol: TCP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
            - containerPort: 853
              protocol: TCP
            - containerPort: 5443
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 67
              protocol: UDP
            - containerPort: 68
              protocol: UDP
            - containerPort: 443
              protocol: UDP
            - containerPort: 784
              protocol: UDP
            - containerPort: 853
              protocol: UDP
            - containerPort: 8853
              protocol: UDP
            - containerPort: 5443
              protocol: UDP
          volumeMounts:
            - mountPath: /opt/adguardhome/work
              name: adguard-work
      volumes:
        - name: adguard-work
          persistentVolumeClaim:
            claimName: adguard-work
---
apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: adguard
  labels:
    app.kubernetes.io/component: home
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard
    app.kubernetes.io/part-of: adguard
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard
  ports:
    - targetPort: 53
      port: 53
      protocol: TCP
      name: dnstcp
    - targetPort: 68
      port: 68
      protocol: TCP
      name: dhcptcp
    - targetPort: 80
      port: 80
      protocol: TCP
      name: http
    - targetPort: 443
      port: 443
      protocol: TCP
      name: https
    - targetPort: 3000
      port: 3000
      protocol: TCP
      name: admin
    - targetPort: 853
      port: 853
      protocol: TCP
      name: dnstls
    - targetPort: 5443
      port: 5443
      protocol: TCP
      name: dnscrypttcp
    - targetPort: 53
      port: 53
      protocol: UDP
      name: dnsudp
    - targetPort: 67
      port: 67
      protocol: UDP
      name: dhcp
    - targetPort: 68
      port: 68
      protocol: UDP
      name: dhcpudp
    - targetPort: 443
      port: 443
      protocol: UDP
      name: httpsudp
    - targetPort: 784
      port: 784
      protocol: UDP
      name: dnsquic1
    - targetPort: 853
      port: 853
      protocol: UDP
      name: dnsquic2
    - targetPort: 8853
      port: 8853
      protocol: UDP
      name: dnsquic3
    - targetPort: 5443
      port: 5443
      protocol: UDP
      name: dnscryptudp
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
