Vagrant.configure(2) do |config|

  config.vm.define "cp-01" do |vm|
    vm.vm.provider :libvirt do |domain|
      domain.cpus = 2
      domain.uri = 'qemu+unix:///system'
      domain.memory = 2048
      domain.storage :file, :device => :cdrom, :path => "/tmp/metal-amd64.iso"
      domain.storage :file, :size => '10G', :type => 'raw'
      domain.boot 'hd'
      domain.boot 'cdrom'
    end
    vm.vm.network :private_network,
      :ip => "192.168.100.2",
      :libvirt__guest_ipv6 => "yes",
      :libvirt__ipv6_address => "fd00::2",
      :libvirt__ipv6_prefix => "64"
  end

  config.vm.define "worker-01" do |vm|
    vm.vm.provider :libvirt do |domain|
      domain.cpus = 2
      domain.uri = 'qemu+unix:///system'
      domain.memory = 4096
      domain.storage :file, :device => :cdrom, :path => "/tmp/metal-amd64.iso"
      domain.storage :file, :size => '10G', :type => 'raw'
      domain.boot 'hd'
      domain.boot 'cdrom'
    end
    vm.vm.network :private_network,
      :ip => "192.168.100.3",
      :libvirt__guest_ipv6 => "yes",
      :libvirt__ipv6_address => "fd00::3",
      :libvirt__ipv6_prefix => "64"
  end

end
