rollOutCiliumPods: true
operator:
  replicas: 1
  rollOutPods: true
k8sServiceHost: "{{ ansible_default_ipv4.address }}"
k8sServicePort: 6443
k8sClientRateLimit:
  qps: 50
  burst: 200
kubeProxyReplacement: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
l2announcements:
  enabled: true
externalIPs:
  enabled: true
gatewayAPI:
  enabled: true
envoy:
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
