Vagrant.configure(2) do |config|

  config.vm.define "k8s-node-01" do |vm|
    vm.vm.provider :libvirt do |domain|
      domain.cpus = 2
      domain.uri = 'qemu+unix:///system'
      domain.memory = 16384
      domain.storage :file, :device => :cdrom, :path => "/home/tamay.mueller/Dokumente/IdeaProjects/k8s/dev-environments/dev-home.tamay.cloud/talos/metal-amd64.iso"
      domain.storage :file, :size => '20G', :type => 'raw'
      domain.boot 'hd'
      domain.boot 'cdrom'
    end
    vm.vm.network :private_network,
      :ip => "192.168.111.2",
      :libvirt__guest_ipv6 => "yes",
      :libvirt__ipv6_address => "fd00::2",
      :libvirt__ipv6_prefix => "64"
  end
end
