Vagrant.configure(2) do |config|

  # General Libvirt Connection
  config.vm.provider :libvirt do |libvirt|
    libvirt.host = "localhost"
    libvirt.uri = 'qemu+unix:///system'
    libvirt.driver = 'kvm'
    libvirt.memory = '4096'
    libvirt.cpus = '2'
  end

  config.vm.define "podman" do |podman|
    podman.vm.box = "generic/rocky9"
    podman.vm.hostname = "podman.example.com"
    podman.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end
